'use strict';

// Shared state for the compression proxy: where it lives on disk, which port it
// actually bound, and the shell snippet that points ANTHROPIC_BASE_URL at it.
//
// Both sides use this module — the daemon supervisor (start/stop/status) and the
// server process itself, which writes the state the moment it is really
// listening. That ordering is the point: nothing claims the proxy is up until a
// socket is bound.

const fs = require('fs');
const net = require('net');
const path = require('path');
const { homedir } = require('../install/paths');

// Default port. NOT 7474 — that is Neo4j's HTTP port, and the collision left
// fresh installs exporting ANTHROPIC_BASE_URL to a port nothing listened on,
// which broke every Claude session with ECONNREFUSED.
const DEFAULT_PORT = 41474;

// Port used by lakonai <= 1.2.2. Kept only so `proxy status` can still see (and
// `proxy stop` still kill) a daemon left over from an older install.
const LEGACY_PORT = 7474;

const MARKER = '# lakonai proxy';

function lakonHome() {
  return process.env.LAKON_HOME || path.join(homedir(), '.lakon');
}

const stateFile = () => path.join(lakonHome(), 'proxy.json');
const legacyPidFile = () => path.join(lakonHome(), 'proxy.pid');
const envFile = () => path.join(lakonHome(), 'proxy-env.sh');

function readState() {
  try {
    const s = JSON.parse(fs.readFileSync(stateFile(), 'utf8'));
    /* istanbul ignore else -- a state file that parses but lacks pid/port falls through to the legacy read */
    if (s && Number(s.pid) && Number(s.port)) {
      return { pid: Number(s.pid), port: Number(s.port), startedAt: s.startedAt || null, version: s.version || null };
    }
  } catch { /* fall through to the legacy file */ }
  // Pre-1.2.3 installs only wrote a bare pid file and always used LEGACY_PORT.
  try {
    const pid = Number(fs.readFileSync(legacyPidFile(), 'utf8').trim());
    if (pid) return { pid, port: LEGACY_PORT, startedAt: null, legacy: true };
  } catch { /* no state at all */ }
  return null;
}

function writeState(state) {
  try {
    fs.mkdirSync(lakonHome(), { recursive: true });
    fs.writeFileSync(stateFile(), JSON.stringify(state));
    return true;
  } catch {
    return false;
  }
}

function clearState() {
  for (const f of [stateFile(), legacyPidFile()]) {
    try { fs.unlinkSync(f); } catch { /* already gone */ }
  }
}

// ── liveness ────────────────────────────────────────────────────────────────

// A real TCP connect. Checking the PID is not enough: a recycled PID reads as
// "running" while nothing is bound, which is exactly the failure this proxy
// shipped with.
function probePort(port, timeoutMs = 400) {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    let done = false;
    const finish = (up) => {
      /* istanbul ignore next -- the second of two racing events (timeout+error); not reproducible on a loopback socket */
      if (done) return;
      done = true;
      socket.destroy();
      resolve(up);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => finish(true));
    /* istanbul ignore next -- a loopback connect always resolves or refuses before the timer; needs a black-holing host to reach */
    socket.once('timeout', () => finish(false));
    socket.once('error', () => finish(false));
    socket.connect(port, '127.0.0.1');
  });
}

// NOTE: no unref() here. An unref'd timer lets Node exit mid-poll, which made
// `lakonai proxy start` return silently with exit 0 and no daemon.
function sleep(ms) {
  return new Promise((resolve) => { setTimeout(resolve, ms); });
}

// Poll until `want` matches whether the port answers, or the deadline passes.
async function waitForPort(port, { timeoutMs = 5000, want = true, intervalMs = 100 } = {}) {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if ((await probePort(port, Math.min(400, timeoutMs))) === want) return true;
    if (Date.now() >= deadline) return false;
    await sleep(intervalMs);
  }
}

function isRunning(pid) {
  if (!pid) return false;
  try { process.kill(pid, 0); return true; } catch { return false; }
}

// ── shell env snippet ───────────────────────────────────────────────────────

// The rc file sources this script; this script exports ANTHROPIC_BASE_URL ONLY
// when something is actually listening. A dead proxy therefore costs the user
// compression, not their whole CLI — the previous unconditional export turned
// any daemon death into ECONNREFUSED on every request.
//
// The port check is shell-native where possible (zsh's ztcp, bash's /dev/tcp)
// and falls back to nc. If no mechanism is available nothing is exported, which
// is the safe direction.
function envScript(port) {
  return `# lakonai proxy — generated by lakonai, safe to delete.
# Points ANTHROPIC_BASE_URL at the local compression proxy, but only while it is
# actually listening. Proxy down = plain direct API access, never a broken CLI.
__lakon_port=${port}
__lakon_up=0

# Never clobber a base URL the user set for another endpoint — only take over
# when nothing is set, or when what is set is our own local proxy.
case "$ANTHROPIC_BASE_URL" in
  ""|http://127.0.0.1:*)
    if [ -n "$ZSH_VERSION" ] && zmodload zsh/net/tcp 2>/dev/null; then
      if ztcp 127.0.0.1 $__lakon_port 2>/dev/null; then
        ztcp -c "$REPLY" 2>/dev/null
        __lakon_up=1
      fi
    elif [ -n "$BASH_VERSION" ] && (exec 3<>/dev/tcp/127.0.0.1/$__lakon_port) 2>/dev/null; then
      __lakon_up=1
    elif command -v nc >/dev/null 2>&1 && nc -z -w 1 127.0.0.1 $__lakon_port >/dev/null 2>&1; then
      __lakon_up=1
    fi
    ;;
esac

if [ "$__lakon_up" = 1 ]; then
  export ANTHROPIC_BASE_URL=http://127.0.0.1:$__lakon_port
fi
unset __lakon_port __lakon_up
`;
}

function writeEnvScript(port) {
  try {
    fs.mkdirSync(lakonHome(), { recursive: true });
    fs.writeFileSync(envFile(), envScript(port));
    return true;
  } catch {
    return false;
  }
}

function removeEnvScript() {
  try { fs.unlinkSync(envFile()); return true; } catch { return false; }
}

module.exports = {
  DEFAULT_PORT,
  LEGACY_PORT,
  MARKER,
  lakonHome,
  stateFile,
  legacyPidFile,
  envFile,
  readState,
  writeState,
  clearState,
  probePort,
  waitForPort,
  isRunning,
  envScript,
  writeEnvScript,
  removeEnvScript,
  sleep,
};
